version: '3.8'

networks:
    bank_api:

services:
    mariadb:
        container_name: bank-api-db
        image: mariadb
        restart: unless-stopped
        tty: true
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
        networks:
            - bank_api

    nginx:
        container_name: bank-api-nginx
        image: nginx:stable-alpine
        ports:
            - '8080:80'
            - '9001:9001'
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mariadb
        networks:
            - bank_api

    php:
        container_name: bank-api-php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - '9000:9000'
        networks:
            - bank_api

    redis:
        container_name: bank-api-redis
        image: redis:7.2.5
        ports:
            - '6379:6379'
        networks:
            - bank_api

    cron:
        container_name: bank-api-cron
        build:
            context: .
            dockerfile: docker/cron/Dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - php
            - mariadb
            - redis
        networks:
            - bank_api

volumes:
    db_data: {}
